name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Download bing wallpaper
        run: php artisan download:bing-wallpaper
      - name: Update README.md
        run: php artisan update:readme
      - name: Git Push
      - run: |
          git config user.name 'Hao Yuqi'
          git config user.email 'hi.haoyuqi+github@gmail.com'
          git commit -m . "Update README.md"
          git push
